# -*- coding: utf-8 -*-
"""Bank_usecase.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDyrho-5p3JwZq2c0xu0Pl7F_0dJClUf
"""

class Bank:
    def __init__(self, atm_pin, Amount=0):
        self.atm_pin = atm_pin
        self.Amount = Amount
    def withdraw(self, atm_pin, withdraw_amount):
        if atm_pin != self.atm_pin:
            return 'Invalid ATM PIN'
        if self.Amount <= 0:
            return 'Zero balance'
        if withdraw_amount > self.Amount:
            return 'Insufficient balance'
        balance = self.Amount - withdraw_amount
        return balance
    def deposit(self, atm_pin, deposit_amount):
        if atm_pin != self.atm_pin:
            return 'Invalid ATM PIN'
        balance = self.Amount + deposit_amount
        return balance
    def get_balance(self):
            return self.Amount

bank1 = Bank(1234, 1000)
print(bank1.withdraw(1234, 500))
print(bank1.deposit(1244, 250))
print(bank1.get_balance())