# -*- coding: utf-8 -*-
"""Test3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13JPpxSN__BkhP1Op_vzZqMqWZu_xNPu-

Q39. Create a class called "Book" with properties for "title", "author", and "publisher". Create a
subclass of
"Book" is called "Ebook" with additional properties for "file_format" and "file_size". Create
objects of both
classes and print out their properties.
"""

## Single inheritance
class Book:
  def __init__(self, title, author, publisher):
    self.title = title
    self.author = author
    self.publisher = publisher
class Ebook(Book):
  def __init__(self, title, author, publisher, file_format, file_size):
    super().__init__(title, author, publisher)
    self.file_format = file_format
    self.file_size = file_size

book1 = Book('Power of your subconscious Mind', 'Dr. Joseph Murphy', 'India Book Distributors')
print(book1.title)
print(book1.author)
print(book1.publisher)

ebook1 = Ebook('Thinking, Fast and Slow', 'Daniel Kahneman', 'Penguin Books', 'PDF', '250kb')
print(ebook1.title)
print(ebook1.author)
print(ebook1.publisher)
print(ebook1.file_format)
print(ebook1.file_size)